# Generated by Django 3.2.3 on 2021-05-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_name', models.CharField(max_length=150, verbose_name='The title of the book')),
                ('year', models.IntegerField(verbose_name='Year of publication of the book')),
                ('number_of_pages', models.IntegerField(verbose_name='Number of pages')),
                ('weight_book', models.IntegerField(verbose_name='Books weight')),
                ('number_of_books_available', models.IntegerField(verbose_name='Number of books available')),
                ('is_available', models.BooleanField(default=False, verbose_name='Is the book available?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Was catalogued')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Was updated')),
            ],
        ),
    ]
