# Generated by Django 3.2.3 on 2021-05-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_publisherfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Author of the book')),
            ],
        ),
    ]
