# Generated by Django 3.2.3 on 2021-05-23 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_authorfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_field',
            field=models.ManyToManyField(to='forms.AuthorField'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forms.genrefield'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='series_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forms.seriesfield'),
            preserve_default=False,
        ),
    ]
