# Generated by Django 3.2.3 on 2021-05-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_book_publisher_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorfield',
            name='author_descrption',
            field=models.TextField(blank=True, null=True, verbose_name='Genre description'),
        ),
        migrations.AddField(
            model_name='genrefield',
            name='genre_descrption',
            field=models.TextField(blank=True, null=True, verbose_name='Genre description'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
