# Generated by Django 3.2.3 on 2021-06-08 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0008_auto_20210525_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_name', models.CharField(max_length=300, verbose_name='The title of the book')),
                ('image', models.ImageField(upload_to='', verbose_name='Book image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('year', models.IntegerField(verbose_name='Year of publication of the book')),
                ('pages', models.IntegerField(verbose_name='Number of pages')),
                ('binding', models.CharField(max_length=100, verbose_name='Book binding')),
                ('format_book', models.CharField(max_length=100, verbose_name='Book format')),
                ('isbn', models.CharField(max_length=25, verbose_name='ISBN')),
                ('weight', models.PositiveIntegerField(verbose_name='Book weight')),
                ('age', models.CharField(max_length=25, verbose_name='Age restrictions')),
                ('number_of_pages', models.IntegerField(verbose_name='Number of pages')),
                ('number_of_books_available', models.IntegerField(verbose_name='Number of books available')),
                ('is_available', models.BooleanField(default=False, verbose_name='Is the book available?')),
                ('rating', models.PositiveIntegerField(verbose_name='Rating (0-10)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Was catalogued')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Was updated')),
                ('author', models.ManyToManyField(related_name='book_author', to='forms.AuthorField')),
                ('genre', models.ManyToManyField(related_name='book_genre', to='forms.GenreField')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_publisher', to='forms.publisherfield')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_series', to='forms.seriesfield')),
            ],
        ),
    ]
