# Generated by Django 3.2.3 on 2021-06-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number_of_pages',
        ),
    ]
