# Generated by Django 3.2.3 on 2021-06-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0003_alter_bookincart_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.TextField(verbose_name='Contact info')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='order created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='order updated')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='carts.cart', verbose_name='Order')),
            ],
        ),
    ]
