# Generated by Django 3.2.3 on 2021-07-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='status_mng',
        ),
        migrations.AddField(
            model_name='order',
            name='status_cancel',
            field=models.BooleanField(default=False, verbose_name='Cencel order?'),
        ),
    ]
