# Generated by Django 3.2.3 on 2021-07-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210705_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_cancel',
            field=models.BooleanField(default=False, verbose_name='Cancel order?'),
        ),
    ]
