# Generated by Django 3.2.3 on 2021-06-15 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone')),
                ('country', models.CharField(blank=True, default='No record', max_length=35, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, default='No record', max_length=35, null=True, verbose_name='City')),
                ('postcode', models.CharField(blank=True, default='No record', max_length=10, null=True, verbose_name='Postcode')),
                ('address_1', models.CharField(blank=True, default='No record', max_length=150, null=True, verbose_name='Address 1')),
                ('address_2', models.CharField(blank=True, default='No record', max_length=150, null=True, verbose_name='Address 2')),
                ('other', models.TextField(blank=True, default='No record', max_length=35, null=True, verbose_name='Other information')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
