# Generated by Django 3.2.3 on 2021-06-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_1',
            new_name='аddress_1',
        ),
    ]
