# Generated by Django 3.2.3 on 2021-06-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='other',
            field=models.TextField(blank=True, default='No record', max_length=200, null=True, verbose_name='Other information'),
        ),
    ]
